name: 💡 機能追加:backend
description: バックエンド側の機能追加用テンプレートです
body:
  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: 対応する機能追加の概要を記載してください。なぜ追加するのか目的がある場合はざっと記載してください。(設計書どおりの実装の場合は目的は書かなくてOK)
      placeholder: |
        例:
        - 新しいAPIエンドポイントを追加する
        - ○○バッチ処理を追加する
    validations:
      required: true

  - type: textarea
    id: detail
    attributes:
      label: 詳細
      description: API仕様や処理内容など、分かっている範囲で記載してください。
      placeholder: |
        例:
        - エンドポイント、リクエスト/レスポンス
        - ビジネスロジックの概要
    validations:
      required: false

  - type: textarea
    id: task
    attributes:
      label: タスク
      description: 必要な作業を箇条書きで記載してください。（分かる範囲でOK）
      placeholder: |
        例:
        - [ ] エンティティ/テーブル定義
        - [ ] 実装
        - [ ] テスト追加
    validations:
      required: false
